DDD_Na_Partica.Web/Controllers/PessoaController.cs
using DDD_Na_Partica.Application.IppServices;
using DDD_Na_Partica.Web.Helpers;
using DDD_Na_Partica.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DDD_Na_Partica.Web.Controllers
{
    public class PessoaController : Controller
    {
        private readonly IAppServicePessoa appServicePessoa;

        public PessoaController(IAppServicePessoa _appServicePessoa)
        {
            appServicePessoa = _appServicePessoa;
        }

        public ActionResult Index()
        {
            var modelList = appServicePessoa.GetList();

            var list = Mapeamento.GetListDtoToListModel(modelList);

            return View(list);
        }

        public ActionResult CadastrarAlterar(int? id)
        {
            if (id == null)
            {
                var model = new PessoaViewModel();
                model.Usuario = new UsuarioViewModel();
                return View(model);
            }
            else
            {
                var model = Mapeamento.PessoaDtoToPessoaViewModel(appServicePessoa.GetPessoaById(id ?? 0));
                return View(model);
            }
        }


    }
}

DDD_Na_Partica.Web/Views/Shared/_Alerta.cshtml
@using DDD_Na_Partica.Web.Models
@using DDD_Na_Partica.Web.Helpers

@{
    var alertas = TempData.ContainsKey(Alerta.TempDataKey)
        ? (List<Alerta>)TempData[Alerta.TempDataKey]
        : new List<Alerta>();

    if (alertas.Any())
    {
        foreach (var alerta in alertas)
        {
            var dismissableClass = alerta.Dismissable ? "alert-dismissable" : null;

            <div class="alert alert-@alerta.AlertaStyle @dismissableClass">
                @if (alerta.Dismissable)
                {
                    <button type="button" class="close" data-dismiss="alert" arial-hidden="true">
                        &times;
                    </button>
                }
                @Html.Raw(alerta.Message)
            </div>
        }
    }
}

DDD_Na_Partica.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @if (HttpContext.Current.User.Identity.IsAuthenticated)
    {
        <div class="navbar navbar-inverse navbar-fixed-top background-black">
            <div class="container">
                <div class="navbar-header">
                    @*<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>*@
                    @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                    @Html.ActionLink("Usuario", "Index", "Usuario", new { area = "" }, new { @class = "navbar-brand" })

                    @Html.ActionLink("Sair", "LogOff", "Account", new { area = "" }, new { @class = "navbar-brand" })
                    @Html.ActionLink("Sair", "Index", "Pessoa", new { area = "" }, new { @class = "navbar-brand" })

                    <span style="color:yellowgreen;">Olá - @HttpContext.Current.User.Identity.Name</span>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav"></ul>
                </div>
            </div>
        </div>
    }
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/tether")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

DDD_Na_Partica.Web/Views/Shared/_LayoutNew.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top" style="background-color:aquamarine;">
        <div class="container">
            <div class="navbar-header">
                    @Html.ActionLink("Usuario", "Index", "Usuario", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content" style="background-color: brown;">
        @RenderBody()
        <hr />      
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/tether")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

DDD_Na_Partica.Web/Views/Shared/_partial_Teste_ViewBag_Data_TempData.cshtml
@model DDD_Na_Partica.Web.Models.TesteViewBag_Data_TempData


<div class="row">
    <h3>@Model.Titulo</h3>
    <br />
    <p class="w-100">
        @Model.Descricao
    </p>
</div>
<div class="row">
    <div class="alert-danger w-50">
        @{foreach (var nome in @Model.lista)
            {
                <label class="col-3">
                    @nome
                </label>
            }
        }
    </div>
</div>